name = "Libglvnd_jll"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.2.0+2"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Xorg_libXext_jll = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
Xorg_libX11_jll = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
Xorg_glproto_jll = "41595b7c-9afa-5287-863f-896d3380052a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
